### ISSUE TITLE
The club slave chore removes owners padlocks

### ISSUE THREAD

**Issue by bananarama92** [Ben987/Bondage-College#3471]
I noticed that the club slave chore will always remove your collar, even when it's locked on with an owners padlock (on normal difficulty, at least). Based on the padlock's description (_i.e._ only owners are generally able to remove it) this sounds like unintended behavior?

**Comment by elliesec** [comment]
That's intentional as far as I'm aware. If wearing a slave collar (or a collar locked on with an owner lock), it will be restored after the club slave period is over, provided the player is still in the same browser session (i.e. hasn't closed or reloaded the game since starting the club slave job).

**Comment by bananarama92** [comment]
> provided the player is still in the same browser session

Ah, so that's why this happened. Is this behavior a deliberate design decision or more of a technical limitation?

**Comment by Ben987** [comment]
Please use Discord for these kinds of questions.  I don't think this is issued a lot.  Thanks!
