### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#485]
![grafik](https://user-images.githubusercontent.com/40240507/68354590-21b60100-010d-11ea-9588-cd768f77f63b.png)

@adokilume Weißt du, wo man die Anfangstexte einfügen muss, wenn man den Button "Ärger suchen" drückt? Die sind leider immer auf englsih.

**Comment by adokilume** [comment]
Das ist merkwürdig, meines Erachtens müssten die eigentlich übersetzt sein und funktionieren wie der Rest, aber ich habe es gerade getestet und du hast recht. Ich werde heute Nachmittag mal nachforschen.

**Comment by adokilume** [comment]
@Ben987 Do you have an idea here? The problem is that when using the "Look for trouble button" and meeting a kidnapper or a club slave for the first time, her intro text is always displayed in English, despite the translation being available. I did a little bit of testing, and it looks like this only affects the first NPC of each category per session. When I met a second kidnapper without logging off, her text was displayed in the correct language. So my guess is that it might have something to do with the translation files not loading fast enough. Is that a possibility, or could it be caused by something else? I'm not sure how to fix it so far.

**Comment by Dallun511** [comment]
@adokilume 
![grafik](https://user-images.githubusercontent.com/40240507/69011587-7b6bc600-096c-11ea-829e-739ff705d81b.png)
Online ist alles english, obwohl du alles übersetzt hast. Hast du vergessen die Scripts irgendwo einzutragen?

Grüße Dallun511

**Comment by adokilume** [comment]
Das kann ich mir leider auf den ersten Blick nicht erklären. Im Skript sind die Dateien richtig eingetragen, und ich meine eigentlich, das auch getestet zu haben. Eventuell hat eins der letzen Updates etwas durcheinandergebracht, da müsste man bei Gelegenheit nochmal forschen.

**Comment by Dallun511** [comment]
Ehrlich gesagt, besteht das Wochen seit Monaten. Ich habe es nur nicht gemeldet, da ich das Feature nicht wirklich nutze.

Ziemlich schade, dass kaum einer sich für die deutsche Übersetzung interessiert.

**Comment by Ben987** [comment]
Does it only happens with kidnappers or all NPCs?  If its only for kidnappers I could certainly do a fix.

**Comment by adokilume** [comment]
When I tested this a while back, it happened with both kidnappers and club slaves on the first encounter each.
The second issue Dallun found is that the Chat Character dialog stays English despite the translations being present and added to the dictionary. I haven't really investigated this one yet.

**Comment by Ben987** [comment]
This should be fixed with the latest version
